version: '3.8'

services:
  backend:
    build: backend/
    ports:
      - 8000:8000
    volumes:
      - ./data:/app/data
    restart: always
    networks:
      - app
    container_name: backend

  frontend:
    build: frontend/
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./data:/app/data
    restart: always
    networks:
      - app
    container_name: frontend

networks:
  app:
    driver: bridge