version: '3.8'

services:
  backend:
    build: backend/
    ports:
      - 8000:8000
    volumes:
#      - ./backend:/app/backend
      - ./data:/app/data
    #command: "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    networks:
      - app
    container_name: backend

  frontend:
    build: frontend/
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
#      - ./frontend:/app
      - ./data:/app/data
    #command: "streamlit run ./frontend/streamlit_app.py"
    restart: always
    networks:
      - app
    container_name: frontend

networks:
  app:
    driver: bridge